name: Build XO Lite

on:
  push:
    branches: [ "release/hydron", "chore/**" ]
    tags: [ "hydron-*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Prepare environment
        run: |
          TAG="${GITHUB_REF##*/}
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Delete latest release and tag
        if: startsWith(github.ref, 'refs/heads/release')
        run: gh release delete ${TAG} --cleanup-tag
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.TAG }}
          tag_name: ${{ env.TAG }}
          body: Whitestack XO Lite RPM build
          draft: false
          prerelease: false
          overwrite_files: true
          files: |
            dist/*
